### ISSUE TITLE
Commerce sample breaks on NullReference in ProductsDetailViewModel

### ISSUE THREAD

**Issue by lesliewinston** [unoplatform/Uno.Samples#136]
Referring to Commerce Sample.

Issue: 
 - Application breaks in ProductsDetailViewModel. 
 - IListFeed<Reviews> is null.
 
Steps to recreate: 
 - On the Products page select an Item so it shows in the Products Detail view.
 - Switch to the Profile page.
 - Switch back to Products page.
 - IListFeed<Reviews> is now null and application breaks.
 
Note:
 - Only one product has an actual review, so for the others it's an empty collection. but that's fine, it's not null.
 
![commerce](https://user-images.githubusercontent.com/3502103/177009305-555fde53-2973-4280-874c-2f6051d1efdb.png)

**Comment by nickrandolph** [comment]
@lesliewinston Thanks for reporting this. Please see the referenced PR in the extensions library for description and fix for this issue.

**Comment by nickrandolph** [comment]
@lesliewinston this update has been pushed in v2.1.1 of the extensions. Leave a comment here if this hasn't fixed your issue

**Comment by lesliewinston** [comment]
Hi Nick, I see you have updated the extensions in Commerce to 2.1.1.
I had tried to do this on my local copy but I updated too many packages and a bunch of stuff was no longer compatible with .net5.0 (skia.host is .net3.1) - anyway it's toast.
Thought I'd start over. Your branch is ahead of master - would I just clone your branch? or wait...
