### ISSUE TITLE
[Commerce App] Pagination stops working after second page on WinUI

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/Uno.Samples#140]
See branch https://github.com/unoplatform/Uno.Samples/tree/dev/xygu/20220705/paginated-feed-listview-2
Run application on WinUI
Scroll deals and note that as you scroll additional items are added but then subsequent scrolling doesn't load any more items
cc @dr1rrb

**Comment by nickrandolph** [comment]
@dr1rrb do you know if this is still an issue?

**Comment by dr1rrb** [comment]
Humm don't remember the outcome of this ... I remember having fixed issue with threading in pagination in mvux which could be related.

As i latests sample the pagination was working properly, including on WinUI, I would close this.
