### ISSUE TITLE
[Windows] Hot Reload Not Working in Commerce Sample App

### ISSUE THREAD

**Issue by Soap-141** [unoplatform/Uno.Samples#141]
## Current behavior

Hot Reload doesn't work in the [Uno Extensions Commerce Sample App](https://github.com/unoplatform/Uno.Samples/tree/master/reference/Uno.Extensions.Commerce) using Visual Studio latest release and preview release. But Hot Reload does work if we create a [sample application](https://github.com/unoplatform/uno.extensions/files/9094308/TestHotReload.zip) with the [Uno Extensions Template](https://platform.uno/docs/articles/external/uno.extensions/doc/Overview/ExtensionsOverviewAndGettingStarted.html#step-by-steps).

- [Uno Extensions Commerce Sample App](https://github.com/unoplatform/Uno.Samples/tree/master/reference/Uno.Extensions.Commerce)

Visual Studio 2022 Current:
![Animation_47](https://user-images.githubusercontent.com/57812285/178532121-ed987479-aceb-42bf-9cdc-d67ed9babdb9.gif)

Visual Studio 2022 Preview:
![Animation_48](https://user-images.githubusercontent.com/57812285/178532479-a4d06be5-d64b-4162-b488-46ca76aac536.gif)

- [Uno Extensions Template Sample App](https://github.com/unoplatform/uno.extensions/files/9094286/TestHotReload.zip)

Visual Studio 2022 Current:
Can't be launched.

Visual Studio 2022 Preview:
![Animation_49](https://user-images.githubusercontent.com/57812285/178533183-357fe081-15c2-49ff-95b7-23fa41c03848.gif)

## Expected behavior

Hot Reload should be working on Windows when using the [Uno Extensions Commerce Sample App](https://github.com/unoplatform/Uno.Samples/tree/master/reference/Uno.Extensions.Commerce).

## How to reproduce it (as minimally and precisely as possible)

1. Clone [Uno Extensions Commerce Sample App](https://github.com/unoplatform/Uno.Samples/tree/master/reference/Uno.Extensions.Commerce)
2. Make sure that Hot Reload is enabled in Visual Studio
3. Open LoginPage.xaml
4. Remove the `x:Uid` at line 60
5. Start the application on Windows
6. Update the `Text` at line 59-60
7. Save your change
8. Notice that the text in application did not change

## Environment

Nuget Package: Required `Uno.Extensions` packages.

Package Version(s): `2.1.0-dev.173`.

Affected platform(s):

- [ ] ~~iOS~~
- [ ] ~~Android~~
- [ ] ~~WebAssembly~~
- [ ] ~~WebAssembly renders for Xamarin.Forms~~
- [x] Windows
- [ ] ~~Build tasks~~

Visual Studio:

- [ ] ~~2017 (version: )~~
- [ ] ~~2019 (version: )~~
- [x] 2022 (version: 17.2.5)
- [x] 2022 (version: 17.3.0 Preview 2.0)
- [ ] ~~for Mac (version: )~~

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

By following [this](https://docs.microsoft.com/en-us/visualstudio/debugger/hot-reload?view=vs-2022#visual-studio-2022-with-a-net-app-when-using-the-debugger) it made the Hot Reload working without having to save my file changes.

**Comment by nickrandolph** [comment]
Closing as HR is being worked on independently from samples
