### ISSUE TITLE
Error when building Wasm project from sqlite sample solution.

### ISSUE THREAD

**Issue by kaki104** [unoplatform/Uno.Samples#25]
Hi

The error message that appears when building is as follows. UWP and Android projects run normally.

Severity	Code	Description	Project	File	Line	Suppression State
Error		[00:00:00.8932914] /bin/bash: mono: command not found	SQLiteSample.Wasm	C:\Users\kaki1\.nuget\packages\uno.wasm.bootstrap\1.3.0-dev.44\build\Uno.Wasm.Bootstrap.targets	125	

Severity	Code	Description	Project	File	Line	Suppression State
Error		System.Exception: Failed to generate wasm layout (More details are available in diagnostics mode or using the MSBuild /bl switch)
   at Uno.Wasm.Bootstrap.ShellTask_vf2f21c9fe5dfda9f4f03ca4a0a082bf6c8fdbbaf.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 573
   at Uno.Wasm.Bootstrap.ShellTask_vf2f21c9fe5dfda9f4f03ca4a0a082bf6c8fdbbaf.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 182	SQLiteSample.Wasm	C:\Users\kaki1\.nuget\packages\uno.wasm.bootstrap\1.3.0-dev.44\build\Uno.Wasm.Bootstrap.targets	125	

### Environment
- Windows 10 version 2004
- Visual Studio 2019 version 16.7.3
- WSL 2
- .Net SDK (3.1.402, 5.0.100)

**Comment by jeromelaban** [comment]
Thanks for the report. We're currently updating all the samples to make sure they build properly, but in the meantime, the issue you're mentioning can be more verbose when updating the `uno.wasm.bootstrap` bootstrap to the latest stable release.

You'll need to update your WSL installation with a command provided by the build once the package is updated.

**Comment by kaki104** [comment]
When searching using the 

> wslconfig /l

 command in PowerShell, Ubuntu should be set to (Default).

To set Ubuntu as (Default), enter 

> wslconfig /s

 "Ubuntu-20.04".

Click [here ](https://github.com/unoplatform/Uno.SQLitePCLRaw.Wasm/issues/13)for more details

**Comment by jeromelaban** [comment]
Thanks for the update. It's been [updated here](https://github.com/unoplatform/uno/blob/master/doc/articles/get-started-with-linux.md) as well.
