### ISSUE TITLE
ControlLibrary Sample for Uno.WinUI

### ISSUE THREAD

**Issue by michael-hawker** [unoplatform/Uno.Samples#305]
https://github.com/unoplatform/Uno.Samples/tree/master/UI/ControlLibrary

Was hoping there'd also be another sample for Uno.WinUI and the new project setup for control libraries for those. Want to ensure we have our setup correct in WCT Labs to support both Uno.UI and Uno.WinUI.  Would be nice to be able to look at both and compare them **side-by-side** in a simple minimal setup like the samples here.

Or maybe can link to where the templates from the VS extension are instead of having in samples from the docs? https://platform.uno/docs/articles/guides/how-to-create-control-libraries.html

Thanks!

Also see #6 (not sure if that's still a problem?)

**Comment by jeromelaban** [comment]
Hi @michael-hawker! The [ControlLibrary](https://github.com/unoplatform/Uno.Samples/tree/master/UI/ControlLibrary) sample is now mostly "deprecated" in the sense that the default Uno template already contains the right of files to make a control library.

Supporting both Uno.UI and Uno.WinUI is another type of scenario that makes things significantly more complex, and we're generally recommending the use of co-located two csproj files to avoid mixing things up. 

We're using [this type of overrides](https://github.com/unoplatform/uno.toolkit.ui/blob/main/src/Directory.Build.props#L85-L93) to ensure that bin/obj files are placed at the right location when using co-located projects.

**Comment by michael-hawker** [comment]
Thanks @jeromelaban, is this the right place to look for the templates in the main repo? https://github.com/unoplatform/uno/tree/master/src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content

Or are those the command line vs. VS ones? Not sure by the naming which ones I should be looking at for the UWP Class Library and WinUI 3 Class Library.
