### ISSUE TITLE
New templates cause blurred / low-res look on Windows when using other than 100% display scaling settings

### ISSUE THREAD

**Issue by MinikPLayer** [unoplatform/Uno.Samples#330]
### Current behavior

When using unoapp template from _Uno.Templates_ or Visual Studio template wizard resulting Windows app is blurred / low-res looking if system display scaling is other than 100%. 

(screenshot showing _Uno.Templates_ unoapp window in the background, and native looking, not blurred window in the foreground)
![image](https://user-images.githubusercontent.com/39161575/232548792-862a1dba-3d4a-4d66-95bc-47b6d6ea9d51.png)

### Expected behavior

App correctly scaling with display scaling

### How to reproduce it (as minimally and precisely as possible)

Follow getting started guide (for example https://platform.uno/docs/articles/get-started-vs-2022.html) and set display scaling to 150% or 200%. App should be blurry.

### Workaround

Use Rider Getting Started guide (https://platform.uno/docs/articles/get-started-rider.html?tabs=windows). App won't be blury in legacy template used in this guide.

EDIT:
Changing `<Manifest Include="$(ApplicationManifest)" />` to `<Manifest Include="app.manifest" />`, `<WindowsAppSDKSelfContained>` to true and deleting **UnoApp.Windows/obj** directory also works.
(See comment https://github.com/unoplatform/Uno.Samples/issues/330)

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.WinUI: 4.8.24

### Affected platforms

Windows

### IDE

Visual Studio 2022

### IDE version

17.5.4

### Anything else we need to know?

Windows 11 22H2
AMD 23.4.2 driver

**Comment by dansiegel** [comment]
I believe this was fixed already by @MartinZikmund in unoplatform/uno.templates#44

**Comment by MartinZikmund** [comment]
Yes, that should fix the problem
