### ISSUE TITLE
Update Commerce to latest packages

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Samples#338]
We should be updating Commerce to latest stable packages for all Uno family packages and then ensure the app is working correctly

**Comment by nickrandolph** [comment]
https://github.com/unoplatform/Uno.Samples/tree/dev/nr/commercereview
Here's a branch that starts to update Commerce sample. Note there's a few issues with navigation that need to be investigated

**Comment by carlh98** [comment]
Here's the PR: https://github.com/unoplatform/Uno.Samples/pull/344

**Comment by carlh98** [comment]
PR was merged
