### ISSUE TITLE
[Commerce] When deploying on IOS, the screen remains black

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/Uno.Samples#418]
![image](https://github.com/unoplatform/Uno.Samples/assets/90481654/cb46abd8-38dd-4403-8ebf-b7aa08288e3d)

Outside the error shown in the comment, no other noticeable error message

**Comment by Marc-Antoine-Soucy** [comment]
2023-08-01 15:02:31.935281-0400 Commerce.Mobile[95053:46340679] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=95053

**Comment by agneszitte** [comment]
@Marc-Antoine-Soucy lack of splashscreen and extended splashscreen can cause this issue.
@nickrandolph workaround this issue for maui embedding samples with this PR : https://github.com/unoplatform/Uno.Samples/pull/565

Related to this issue : https://github.com/unoplatform/uno.extensions/issues/1865

**Comment by jeromelaban** [comment]
Let's close this issue in favor of https://github.com/unoplatform/uno.extensions/issues/1865
