### ISSUE TITLE
[UI/EFCoreSQLiteSample] Does not build on WASM 

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/Uno.Samples#463]
It says:
 1>C:\Users\ma.soucy\.nuget\packages\uno.wasm.bootstrap\7.0.24\build\Uno.Wasm.Bootstrap.targets(206,3): error : System.InvalidOperationException: The current PowerShell Execution policy is [Restricted]. To run the bootstrapper, open an elevated PowerShell prompt and run `Set-ExecutionPolicy RemoteSigned -Force` 

Is this normal @nickrandolph

**Comment by Marc-Antoine-Soucy** [comment]
I think this might just be normal. Not sure if I should close this or investigate why this happens with this app and not others.

**Comment by jeromelaban** [comment]
This is an expected behavior that is related to your system's configuration. If you apply the recommendation, you'll be able to run the app.
