### ISSUE TITLE
When using the ProgressRing I can't see it on iOS

### ISSUE THREAD

**Issue by LeomarisReyes** [unoplatform/Uno.Samples#529]
The ProgressRing on IOS isn't displaying correctly, while the full UI looks perfect. I've checked the [official documentation](https://platform.uno/docs/articles/features/progressring.html), and it seems that both Android and iOS should support it. However, I'm not seeing it reflected in my app. 

I'm using a simple code in this project:
https://github.com/unoplatform/Uno.Samples/pull/504

I'll be waiting for your comments!

**Comment by jeromelaban** [comment]
Hi @LeomarisReyes! Could you update your sample to .NET 7 (start from a blank Uno template in Visual Studio)?

**Comment by nickrandolph** [comment]
@ajpinedam where you investigating this? If so, do we have an Uno issue associated with this issue

**Comment by ajpinedam** [comment]
@nickrandolph, there was a problem. We opened a GH issue https://github.com/unoplatform/uno/issues/13578 but closed it when we realized the problem was no longer present on the latest version of Uno (4.10).

Closing this issue as it's not relevant anymore. Thanks
