### ISSUE TITLE
[Android][Workshops] AutoLayout issue for the alignment

### ISSUE THREAD

**Issue by hsatopo** [unoplatform/Uno.Samples#614]
I downloaded the sample directly from the repository, and updated the `appsettings.json`, no other changes made. But found below issues

1. For Error template, the layout is messed up. The error icon and the text is not in the center but to the right and the text is off screen. See below screenshot
![Error](https://github.com/unoplatform/Uno.Samples/assets/88302088/b2c1966c-d122-412c-95d7-5aeddd9decbd)
This happens on Android emulator and android device, but not on WASM and Windows. Didn't test MacCatalyst and iOS.

**Comment by agneszitte** [comment]
Uno related blocking issue: https://github.com/unoplatform/uno/issues/14373 (cc @jeromelaban / @MartinZikmund)

**Comment by agneszitte** [comment]
@hsatopo I created a separate issue for the search as it is two different issues.
https://github.com/unoplatform/Uno.Samples/issues/615

**Comment by carldebilly** [comment]
Found what is happening, but still wondering why. When it works (on Android), the layout requires two layout phases to stabilize correctly. The first pass does not use the correct dimensions.

For an unknown reason, the layout never stabilizes in this project. There's an endless loop of layout revalidation, always with the faulty dimensions.

AutoLayout does not seem to be the source of the problem.

Further investigations in Uno is required to fix this problem and it could have broader implications. For sure there's a perf degradation, even when it works correctly.

**Comment by carldebilly** [comment]
May be fixed by https://github.com/unoplatform/uno/pull/14902 / issue https://github.com/unoplatform/uno/issues/14373

**Comment by agneszitte** [comment]
Issue will be fixed and included in the next stable version

**Comment by jeromelaban** [comment]
It's now released in Uno Platform 5.1
