### ISSUE TITLE
[TubePlayer] Search not working after using personal Google API Key

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/Uno.Samples#615]
From [hsatopo](https://github.com/hsatopo)
>I downloaded the sample directly from the repository, and updated the `appsettings.json`, no other changes made. But found below issues
> 2. Search not working after I used my own google api key
>![Search](https://github.com/unoplatform/Uno.Samples/assets/88302088/2918dcf0-f80b-4c6e-ad78-1561e5ee6c74)

**Comment by agneszitte** [comment]
cc @nickrandolph

**Comment by hsatopo** [comment]
@kazo0 Using the same key, by following the workshop on Uno's official website, I can get search working, but media player is not working. Maybe I did something wrong with the replacement of the key.

**Comment by hsatopo** [comment]
@kazo0 I know why it wasn't working now. I edited the wrong file, it should be `appsettings.development.json`, not `appsettings.json`

**Comment by hsatopo** [comment]
@kazo0 btw, is Mac AppKit still a target in Uno 5.0, it seems only MacCatalyst is supported

**Comment by hsatopo** [comment]
@kazo0 after editing the correct file, I was able to get search working. But media playback is not working. Will open a separate issue

**Comment by hsatopo** [comment]
@agneszitte please close this issue as I got it working
