### ISSUE TITLE
[Desktop] Videos don't play with latest packages

### ISSUE THREAD

**Issue by rajamatt** [unoplatform/Uno.Samples#725]
Noticed for TubePlayer when updating to latest packages for Single Project migration.

- Desktop: no video controls on Desktop (clicking on video does nothing either)

Desktop:
![image](https://github.com/unoplatform/Uno.Samples/assets/70542961/a1f9e3fe-553b-4617-b69b-8ad6030bae86)

**Comment by rajamatt** [comment]
I will try to create a small repro app for this.

**Comment by rajamatt** [comment]
Just started investigating this and I found that Skia Desktop doesn't support MediaPlayerElement? https://platform.uno/docs/articles/controls/MediaPlayerElement.html

**Comment by jeromelaban** [comment]
@rajamatt this is expected at this time, yes.
