### ISSUE TITLE
[Windows] [ToDo] Crash when resizing the window on the HomePage

### ISSUE THREAD

**Issue by rajamatt** [unoplatform/Uno.Samples#760]
The HomePage has three states, ExtraWide, Wide, and Narrow. When making the window smaller to the point where the Narrow state takes over, the app crashes. 

Adding the following **MinWidth** Setter prevents the crash, but maybe a better solution can be found.

```xml
<VisualState x:Name="Narrow">
    <VisualState.StateTriggers>
        <AdaptiveTrigger MinWindowWidth="0" />
    </VisualState.StateTriggers>
    <VisualState.Setters>
        <Setter Target="TaskListColumn.MinWidth" Value="*" />
    </VisualState.Setters>
</VisualState>
```

**Comment by agneszitte** [comment]
@rajamatt fixed with https://github.com/unoplatform/Uno.Samples/pull/766
