### ISSUE TITLE
UnoMaterialSample needs to be updated with the Material Toolkit

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Samples#90]
UnoMaterialSample is no longer a valid sample as the most up-to-date packages for Uno.Material no longer contain the `Card`, `Chip`, `ChipGroup`, or `Divider` controls.

We either need to make a new UnoMaterialToolkitSample for those scenarios or include the Uno.Toolkit.UI.Material package within the UnoMaterialSample project.

**Comment by jeromelaban** [comment]
@kazo0 is it that the https://github.com/unoplatform/Uno.Samples/tree/master/UI/UnoMaterialSample is not up to date? Is it still the case?

**Comment by kazo0** [comment]
Looks like it was updated and is now using the Toolkit so it should be good now

**Comment by jeromelaban** [comment]
Excellent, let's close this issue then.
